---
# Playbook: 핵심 인프라 구축 (Docker, MinIO, MariaDB Master/Slave, Node Exporter)

# ----------------------------------------------------
# 0. 공통 준비 작업: EPEL 활성화 및 캐시 갱신 (DNF 설치 오류 방지)
# ----------------------------------------------------
- name: 0. Enable EPEL repository and Clean Cache
  hosts: all
  become: yes
  tasks:
    - name: 0.1. Install EPEL release package
      ansible.builtin.dnf:
        name: epel-release
        state: latest
    

# ----------------------------------------------------
# 1. 모든 서버에 Node Exporter 설치 (DNF 실패 시 수동 설치로 자동 대체)
# ----------------------------------------------------
- name: 1. Install Node Exporter on all VMs
  hosts: all
  become: yes
  vars:
    node_exporter_version: "1.6.1"

  tasks:
    # 1.1. DNF를 이용한 설치 시도 (1차 시도)
    - name: 1.1. Try installing Node Exporter via DNF
      ansible.builtin.dnf:
        name: prometheus-node-exporter
        state: latest
      register: dnf_result
      ignore_errors: true

    # 1.2. DNF 실패 시 수동 다운로드 및 설치 (2차 비상 시도)
    - name: 1.2. Manual Download and Install Node Exporter if DNF failed
      when: dnf_result is failed
      block:
        - name: Create necessary node_exporter user
          ansible.builtin.user:
            name: node_exporter
            shell: /bin/false
            home: /
            create_home: no
          
        - name: Download and Extract Node Exporter binary
          ansible.builtin.unarchive:
            src: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
            dest: "/usr/local/bin"
            remote_src: true
            extra_opts: [--strip-components=1]
            creates: /usr/local/bin/node_exporter
            
        - name: Create Node Exporter service file
          ansible.builtin.copy:
            content: |
              [Unit]
              Description=Node Exporter
              After=network.target
              [Service]
              ExecStart=/usr/local/bin/node_exporter
              User=node_exporter
              Group=node_exporter
              [Install]
              WantedBy=multi-user.target
            dest: /etc/systemd/system/node_exporter.service

        - name: Start Node Exporter service
          ansible.builtin.systemd:
            name: node_exporter
            daemon_reload: yes
            state: started
            enabled: yes


# ----------------------------------------------------
# 2. VM 3 (Web/Storage/Slave DB) 설정 - IP: 192.168.30.100
# ----------------------------------------------------
- name: 2. Configure Docker, MinIO, and MariaDB Slave on VM 3
  hosts: web_storage
  become: yes
  vars:
    minio_access_key: "MINIOACCESS_KEY_CHANGE_ME" 
    minio_secret_key: "MINIOSECRET_KEY_CHANGE_ME"
    maria_db_root_password: "YourStrongRootPassword_ChangeMe" 

  tasks:
    # Docker 설치
    - name: Install DNF utilities
      ansible.builtin.dnf:
        name: dnf-utils
        state: latest
        
    - name: Add Docker official repository and Install Docker-CE
      ansible.builtin.shell:
        cmd: |
          dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
          dnf install -y docker-ce docker-ce-cli containerd.io

    - name: Start Docker service
      ansible.builtin.systemd:
        name: docker
        state: started
        enabled: yes

    # MinIO 설치
    - name: Install MinIO Server and Client
      ansible.builtin.get_url:
        url: "https://dl.min.io/server/minio/release/linux-amd64/minio"
        dest: /usr/local/bin/minio
        mode: '0755'
    
    - name: Create MinIO environment file and start service
      ansible.builtin.copy:
        content: |
          MINIO_VOLUMES="/mnt/data"
          MINIO_OPTS="--address 192.168.30.100:9000 --console-address 192.168.30.100:9001"
          MINIO_ACCESS_KEY={{ minio_access_key }}
          MINIO_SECRET_KEY={{ minio_secret_key }}
        dest: /etc/default/minio
      notify: Restart MinIO Service
      
    # MariaDB Slave 설치 및 설정 (VM 3)
    - name: Install MariaDB Server on VM 3 (Slave)
      ansible.builtin.dnf:
        name: mariadb-server
        state: latest

    - name: Configure MariaDB for Slave Replication (VM 3)
      ansible.builtin.copy:
        content: |
          [mariadb]
          bind-address=0.0.0.0
          server_id=3 
        dest: /etc/my.cnf.d/00-replication.cnf
        mode: '0644'
      notify: Restart MariaDB Service

    - name: Start MariaDB Service on VM 3
      ansible.builtin.systemd:
        name: mariadb
        state: started
        enabled: yes
      notify: Restart MariaDB Service 

    # ❗오류 방지: 서비스 재시작 완료를 강제합니다.
    - name: Ensure MariaDB restart is completed before setting root password
      ansible.builtin.meta: flush_handlers

    # ✅ 권한 설정: 재실행 시 오류를 피하기 위해 mysql_user 모듈 사용 (VM 3)
    - name: Secure MariaDB Installation and set root password on VM 3
      community.mysql.mysql_user:
        name: root
        password: "{{ maria_db_root_password }}"
        host: "{{ item }}"
        login_unix_socket: /var/lib/mysql/mysql.sock # 최초 실행 시 unix_socket 이용
      loop:
        - 127.0.0.1
        - ::1
        - localhost

  handlers:
    - name: Restart MinIO Service
      ansible.builtin.systemd:
        name: minio
        state: restarted
        enabled: yes
        daemon_reload: yes

    - name: Restart MariaDB Service
      ansible.builtin.systemd:
        name: mariadb
        state: restarted


# ----------------------------------------------------
# 3. VM 4 (DB/Backup)에 MariaDB Master 설치 및 설정 - IP: 192.168.30.98
# ----------------------------------------------------
- name: 3. Configure MariaDB Master on VM 4
  hosts: db_backup 
  become: yes
  vars:
    maria_db_root_password: "YourStrongRootPassword_ChangeMe" 

  tasks:
    - name: Install MariaDB Server
      ansible.builtin.dnf:
        name: mariadb-server
        state: latest

    # MariaDB Master 설정 (바이너리 로깅 활성화 및 Server ID 설정)
    - name: Configure MariaDB for Master Replication (VM 4)
      ansible.builtin.copy:
        content: |
          [mariadb]
          bind-address=0.0.0.0
          server_id=4
          log_bin=mariadb-bin
          binlog_format=ROW
        dest: /etc/my.cnf.d/00-replication.cnf
        mode: '0644'
      notify: Restart MariaDB Service

    - name: Start MariaDB Service
      ansible.builtin.systemd:
        name: mariadb
        state: started
        enabled: yes
      notify: Restart MariaDB Service

    # ❗오류 방지: 서비스 재시작 완료를 강제합니다.
    - name: Ensure MariaDB restart is completed before setting root password (VM 4)
      ansible.builtin.meta: flush_handlers

    # ✅ 권한 설정: 재실행 시 오류를 피하기 위해 mysql_user 모듈 사용 (VM 4)
    - name: Secure MariaDB Installation and set root password (VM 4)
      community.mysql.mysql_user:
        name: root
        password: "{{ maria_db_root_password }}"
        host: "{{ item }}"
        login_unix_socket: /var/lib/mysql/mysql.sock
      loop:
        - 127.0.0.1
        - ::1
        - localhost

    # 복제 전용 사용자 생성
    - name: Create replication user on Master (VM 4)
      community.mysql.mysql_user:
        name: repl
        password: "replication_password"
        host: "192.168.30.%" # 192.168.30.x 네트워크 접속 허용
        priv: "*.*:REPLICATION SLAVE"
        state: present
        login_user: root
        login_password: "{{ maria_db_root_password }}"
        login_host: 127.0.0.1 

  handlers:
    - name: Restart MariaDB Service
      ansible.builtin.systemd:
        name: mariadb
        state: restarted
